### ISSUE TITLE
Lift version constraint when installing `ember-cli-chai`

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli-mocha#154]
We currently install `ember-cli-chai: ^0.2.0`, but today v0.3.0 was published that is not included in that version constraint. Should we just update the constraint and do a release whenever a new `ember-cli-chai` is released, or should we remove the constraint and install whatever is the most recent stable release?

/cc @rwjblue @Dhaulagiri

**Comment by rwjblue** [comment]
If the difference between 0.2.0 and 0.3.0 is not breaking, then it seems that ember-cli-chai should not have released a version that inferred breaking backwards compat.

We should generally not just use latest, because that is future hostile (imagine if we actually do need to change the way the two projects are coupled, how could we do that if older versions are going to install the newer ones?).

**Comment by Turbo87** [comment]
We have discussed this a little more via Slack and have come to the conclusion that lifting the version constraint would not be a good idea for now.
