### ISSUE TITLE
Install hangs on ember-cli@2.10.0

### ISSUE THREAD

**Issue by JakeDluhy** [ember-cli/ember-cli-mocha#159]
I'm seeing `ember-cli-mocha` hang with a new project generated with `ember-cli` version 2.10.0. I run the commands
```
ember new mocha-test
cd mocha-test
ember install ember-cli-mocha
```
and it hangs on
`runTopLevelLifecycles: sill install printInstalled` after having Installed packages for tooling via npm.
`ember -v` outpus
```
ember-cli: 2.10.0
node: 6.9.1
os: darwin x64
```
I'd be happy to look into it myself, but I'm not really sure where to start

**Comment by Turbo87** [comment]
@JakeDluhy that is unfortunately a bug in Ember CLI 2.10. instead of asking you to overwrite a certain file it will just show the NPM progress bar instead. As a temporary workaround you can press <kbd>Enter</kbd> and it should continue to install.

@nathanhammond @stefanpenner @rwjblue this is precisely the bug I was talking about last week

**Comment by JakeDluhy** [comment]
Worked, thanks!

**Comment by nathanhammond** [comment]
@Turbo87 This is already addressed by moving to `execa`, confirm?

**Comment by Turbo87** [comment]
@nathanhammond correct, but IIRC that is only on the `beta` branch at the moment

**Comment by nathanhammond** [comment]
Correct, I meant to release that so that we can consider moving it to `release`. *sigh*

**Comment by Turbo87** [comment]
closing as this is an issue in Ember CLI, not in this addon itself
